name: Android CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ dev, ci-workflow ]

jobs:
  test:
    name: Android Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test --stacktrace

  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get secrets
      env:
        unsplash_access: ${{ secrets.API_UNSPLASH_ACCESS }} 
        unsplash_secret: ${{ secrets.API_UNSPLASH_SECRET }}
      run:
        echo "api.unsplash.access=\"$unsplash_access\"\n" > ./local.properties 
        echo "api_unsplash_secret=\"$unsplash_secret\"\n" > ./local.properties
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
