name: Android CI

on:
  push:
    branches: [ master, dev ]
  pull_request:

jobs:
## Android Run Unit Tests
  test:
    name: Android Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get secrets
        env:
          unsplash_access: ${{ secrets.API_UNSPLASH_ACCESS }}
          unsplash_secret: ${{ secrets.API_UNSPLASH_SECRET }}
        run: echo api.unsplash.access=\"$unsplash_access\" >> ./local.properties \
              && echo -e "\n" >> ./local.properties \
              && echo api.unsplash.secret=\"$unsplash_secret\" >> ./local.properties

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test --stacktrace

## Android Build
  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get secrets
      env:
        unsplash_access: ${{ secrets.API_UNSPLASH_ACCESS }}
        unsplash_secret: ${{ secrets.API_UNSPLASH_SECRET }}
      run: echo api.unsplash.access=\"$unsplash_access\" >> ./local.properties \
            && echo -e "\n" >> ./local.properties \
            && echo api.unsplash.secret=\"$unsplash_secret\" >> ./local.properties

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean with Gradle
      run: ./gradlew clean --stacktrace

    - name: Build with Gradle
      run: ./gradlew build --stacktrace
